### ISSUE TITLE
Could not load file or assembly System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0

### ISSUE THREAD

**Issue by pssp-sven** [SuRGeoNix/Flyleaf#111]
Hi @SuRGeoNix,

the following error is thrown, when the target framework is set to net5.0-windows (Winforms). Using net6.0-windows does work.
```
System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
  Source=Vortice.DirectX
  StackTrace:
   at Vortice.Multimedia.WaveFormat.MarshalToPtr()
   at Vortice.XAudio2.IXAudio2.CreateSourceVoice(WaveFormat sourceFormat, VoiceFlags flags, Single maxFrequencyRatio, Boolean enableCallbackEvents, EffectDescriptor[] effectDescriptors)
   at Vortice.XAudio2.IXAudio2.CreateSourceVoice(WaveFormat sourceFormat, Boolean enableCallbackEvents)
   at FlyleafLib.MediaPlayer.Audio.Initialize(Int32 sampleRate) in C:\work\Playground\GitHub\Flyleaf\FlyleafLib\MediaPlayer\Audio.cs:line 225
   at FlyleafLib.MediaPlayer.Audio..ctor(Player player) in C:\work\Playground\GitHub\Flyleaf\FlyleafLib\MediaPlayer\Audio.cs:line 200
   at FlyleafLib.MediaPlayer.Player..ctor(Config config) in C:\work\Playground\GitHub\Flyleaf\FlyleafLib\MediaPlayer\Player.cs:line 410
   at FlyleafPlayer__Custom_.Form1..ctor() in C:\work\Playground\GitHub\Flyleaf\Samples\FlyleafPlayer (Custom)  (WinForms)\Form1.cs:line 26
   at FlyleafPlayer__Custom_.Program.Main() in C:\work\Playground\GitHub\Flyleaf\Samples\FlyleafPlayer (Custom)  (WinForms)\Program.cs:line 20
```
You can easily check this, when you change the target framework in your sample 'FlyleafPlayer (Custom) (WinForms)'.

**Comment by SuRGeoNix** [comment]
This is not happening on new project right, just one that you already have other packages as well? I have seen that after the latest vortice update and I solved it by installing the package System.Runtime.CompilerServices.Unsafe. Let me know if that fixes it.

**Comment by pssp-sven** [comment]
Yes, thanks, that does fix it.
