### ISSUE TITLE
Cannot open any file, Renderer.ReportLiveObjects() throws an COM-Exception

### ISSUE THREAD

**Issue by f1nalspace** [SuRGeoNix/Flyleaf#161]
On my work machine, the current master branch instantly reports a error when i load up any video file (Debug configuration only).
After analyzing, i found the culprit: Renderer.ReportLiveObjects() throws an unhandled COM-Exception :-(

```
SharpGen.Runtime.SharpGenException
  HResult=0x80070057
  Message=HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid arguments], Message: [Falscher Parameter.
]
  Source=SharpGen.Runtime
  StackTrace:
   at SharpGen.Runtime.Result.ThrowFailureException()
   at Vortice.DXGI.Debug.IDXGIDebug.ReportLiveObjects(Guid apiid, ReportLiveObjectFlags flags)
   at FlyleafLib.MediaFramework.MediaRenderer.Renderer.ReportLiveObjects() in C:\Users\GIHXIY1\source\repos\Flyleaf\FlyleafLib\MediaFramework\MediaRenderer\Renderer.Static.cs:line 176
   at FlyleafLib.MediaFramework.MediaDecoder.VideoDecoder.DisposeInternal() in C:\Users\GIHXIY1\source\repos\Flyleaf\FlyleafLib\MediaFramework\MediaDecoder\VideoDecoder.cs:line 1141
   at FlyleafLib.MediaFramework.MediaDecoder.DecoderBase.Dispose(Boolean closeStream) in C:\Users\GIHXIY1\source\repos\Flyleaf\FlyleafLib\MediaFramework\MediaDecoder\DecoderBase.cs:line 135
   at FlyleafLib.MediaFramework.MediaContext.DecoderContext.Stop() in C:\Users\GIHXIY1\source\repos\Flyleaf\FlyleafLib\MediaFramework\MediaContext\DecoderContext.cs:line 1214
   at FlyleafLib.MediaPlayer.Player.Initialize(Status status, Boolean andDecoder) in C:\Users\GIHXIY1\source\repos\Flyleaf\FlyleafLib\MediaPlayer\Player.cs:line 636

  This exception was originally thrown at this call stack:
    [External Code]
    FlyleafLib.MediaFramework.MediaRenderer.Renderer.ReportLiveObjects() in Renderer.Static.cs
    FlyleafLib.MediaFramework.MediaDecoder.VideoDecoder.DisposeInternal() in VideoDecoder.cs
    FlyleafLib.MediaFramework.MediaDecoder.DecoderBase.Dispose(bool) in DecoderBase.cs
    FlyleafLib.MediaFramework.MediaContext.DecoderContext.Stop() in DecoderContext.cs
    FlyleafLib.MediaPlayer.Player.Initialize(FlyleafLib.MediaPlayer.Status, bool) in Player.cs
```

**Comment by SuRGeoNix** [comment]
There is a possibility that debug layer requires something to be initialized (Device/SwapChain) before the call and somehow you call it before that. I will just add a try catch but maybe you just need to install the SDK.
