### ISSUE TITLE
SharpGen.Runtime.SharpGenException HRESULT: [0x887A0001], Module: [Vortice.DXGI], ApiCode: [DXGI_ERROR_INVALID_CALL/InvalidCall]

### ISSUE THREAD

**Issue by goodtogood** [SuRGeoNix/Flyleaf#206]
hi, @SuRGeoNix 

great work! 
I came across the problem described below.
It crashed when running the latest [FlyleafPlayer.exe Flyleaf_v3.5.8_ffmpeg5.7z](https://github.com/SuRGeoNix/Flyleaf/releases/download/v3.5.8/Flyleaf_v3.5.8_ffmpeg5.7z).
there's nothing valuable, all log is as follows,

OS:  windows 8.1 64bit 
RAM: 32Gb 
GPU: Nvidia 2070 Super

```

09.52.47.430 | Info  | [FlyleafEngine] FlyleafLib 3.5.8
09.52.47.435 | Info  | [FlyleafEngine] Loading FFmpeg libraries from ':FFmpeg'
09.52.47.467 | Info  | [FlyleafEngine] FFmpeg Loaded (Location: L:\temp\Flyleaf_v3.5.8_ffmpeg5\FFmpeg, Ver: 59.24.100, #Files: 8)
09.52.47.492 | Info  | [FlyleafEngine] GPU Adapters
[#1] NVIDIA NVIDIA GeForce RTX 2070 (Id: 7943 | Luid: 49381) | DVM: 7.77 GB
[#2] NVIDIA NVIDIA GeForce RTX 2070 SUPER (Id: 7812 | Luid: 52434) | DVM: 7.77 GB
[#3] Unknown Microsoft Basic Render Driver (Id: 140 | Luid: 52289) | DVM: 0 B

09.52.47.523 | Info  | [FlyleafEngine] Audio Devices
{0.0.0.00000000}.{4575da2c-02cf-4ca9-ab18-a10acd0e9565} | Realtek Digital Output (Realtek High Definition Audio) 
{0.0.0.00000000}.{6aace39b-9b69-483c-ad06-f3a054153e56} |  (Realtek High Definition Audio) *
{0.0.0.00000000}.{da75e2ef-f47b-41a5-9a47-2e53ea729f38} | Realtek Digital Output(Optical) (Realtek High Definition Audio) 

09.52.47.745 | Info  | [FlyleafEngine] Plugin loaded (OpenDefault - 3.5.8.0)
09.52.47.745 | Info  | [FlyleafEngine] Plugin loaded (OpenSubtitles - 3.5.8.0)
09.52.47.745 | Info  | [FlyleafEngine] Plugin loaded (StreamSuggester - 3.5.8.0)
09.52.47.768 | Info  | [FlyleafEngine] Plugin loaded (BitSwarm - 1.3.0.0)
09.52.47.769 | Info  | [FlyleafEngine] Plugin loaded (OpenSubtitlesOrg - 1.2.0.0)
09.52.47.779 | Info  | [FlyleafEngine] Plugin loaded (SubtitlesConverter - 1.0.0.0)
09.52.47.780 | Info  | [FlyleafEngine] Plugin loaded (YoutubeDL - 1.3.0.0)
09.52.47.883 | Info  | [FlyleafEngine] Thread started
09.52.47.895 | Debug | [#1]     [Player        ] Creating Player (Usage = AVS)
09.52.47.897 | Info  | [#1]     [Player        ] Initialiazing audio (Default @ 48000Hz)
09.52.47.932 | Debug | [#1]     [Renderer      ] Initializing
09.52.47.989 | Debug | [#1]     [Renderer      ] Adapter Info
[Adapter-49381] NVIDIA GeForce RTX 2070 System: 0 B Video: 7.77 GB Shared: 15.97 GB
[Output ] \\.\DISPLAY1 (X=0, Y=0) 2560x1440 [16:9]

09.52.48.007 | Error | [#1]     [Renderer      ] D3D11 Video Processor Initialization Failed
09.52.48.013 | Info  | [#1]     [Renderer      ] Initialized with Feature Level 11.0
09.52.48.015 | Debug | [#1]     [Player        ] Created
09.52.48.277 | Info  | [#1]     [Renderer      ] Initializing 8-bit swap chain with 2 buffers
```

I cloned the latest code [d8737f2](https://github.com/SuRGeoNix/Flyleaf/commit/d8737f2beece5bb853697833bfe4aec5f70ac987) and debug,  I got an exception below

![20221014102810](https://user-images.githubusercontent.com/10088733/195748191-985ddac9-5895-4f59-aba4-1b5299cf3942.jpg)

```
SharpGen.Runtime.SharpGenException HRESULT: [0x887A0001], Module: [Vortice.DXGI], ApiCode: [DXGI_ERROR_INVALID_CALL/InvalidCall]

at SharpGen.Runtime.Result.ThrowFailureException()
   at SharpGen.Runtime.Result.CheckError()
   at Vortice.DXGI.IDXGIFactory2.CreateSwapChainForHwnd(IUnknown device, IntPtr wnd, SwapChainDescription1 desc, Nullable`1 fullscreenDesc, IDXGIOutput restrictToOutput)
   at FlyleafLib.MediaFramework.MediaRenderer.Renderer.InitializeSwapChain() in E:\Github\Flyleaf\FlyleafLib\MediaFramework\MediaRenderer\Renderer.cs:line 392
   at FlyleafLib.MediaFramework.MediaRenderer.Renderer.SetControl(Control control) in E:\Github\Flyleaf\FlyleafLib\MediaFramework\MediaRenderer\Renderer.cs:line 169
   at FlyleafLib.MediaFramework.MediaDecoder.VideoDecoder.CreateRenderer(Control control) in E:\Github\Flyleaf\FlyleafLib\MediaFramework\MediaDecoder\VideoDecoder.cs:line 85
   at FlyleafLib.MediaPlayer.Player.SetControl(Flyleaf oldValue, Flyleaf newValue) in E:\Github\Flyleaf\FlyleafLib\MediaPlayer\Player.cs:line 452
   at FlyleafLib.MediaPlayer.Player.set_Control(Flyleaf value) in E:\Github\Flyleaf\FlyleafLib\MediaPlayer\Player.cs:line 30
   at FlyleafLib.Controls.WPF.VideoView.OnPlayerChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) in E:\Github\Flyleaf\FlyleafLib\Controls\WPF\VideoView.cs:line 70
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Baml2006.WpfMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
```
would you like to give some tips?
thanks!

**Comment by SuRGeoNix** [comment]
Hi @goodtogood and thanks!

1) Enable native code debugging and see more details for the error coming from DirectX (it requires an SDK for debugging that you might not have in Win8.1 though).

2) I suspect that in your case (Win8.1) it should go at the first case but it goes at the else part of if statement. Force it to go at the first one and see how it goes.

```csharp
if (true || Device.FeatureLevel < FeatureLevel.Level_10_0 || (!string.IsNullOrWhiteSpace(Config.Video.GPUAdapter) && Config.Video.GPUAdapter.ToUpper() == "WARP"))
{
	swapChainDescription.BufferCount= 1;
	swapChainDescription.SwapEffect = SwapEffect.Discard;
	swapChainDescription.Scaling    = Scaling.Stretch;
}
else
{
	swapChainDescription.BufferCount= Config.Video.SwapBuffers; // TBR: for hdr output or >=60fps maybe use 6
	swapChainDescription.SwapEffect = SwapEffect.FlipDiscard;
	swapChainDescription.Scaling    = Scaling.None;
}
```

3) Try to force to use the 2nd gpu adapter instead of the 1st one by setting the Config.Video.GPUAdapter = "SUPER"

**Comment by SuRGeoNix** [comment]
Closing this and can re-open it after your feedback.
