### ISSUE TITLE
App is crashed after getting this error SharpGen.Runtime.SharpGenException: HRESULT: [0x887A0001],

### ISSUE THREAD

**Issue by ansdy29** [SuRGeoNix/Flyleaf#387]
SharpGen.Runtime.SharpGenException: HRESULT: [0x887A0001], Module: [Vortice.DXGI], ApiCode: [DXGI_ERROR_INVALID_CALL/InvalidCall], Message: [The application made a call that is invalid. Either the parameters of the call or the state of some object was incorrect.
Enable the D3D debug layer in order to see details via debug messages.
]
   at SharpGen.Runtime.Result.ThrowFailureException()
   at Vortice.DXGI.IDXGISwapChain.GetBuffer[T](Int32 index)
   at FlyleafLib.MediaFramework.MediaRenderer.Renderer.ResizeBuffers(Int32 width, Int32 height)
   at FlyleafLib.MediaFramework.MediaRenderer.Renderer.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam, IntPtr uIdSubclass, IntPtr dwRefData)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at FlyleafLib.Utils.NativeMethods.DefSubclassProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at FlyleafLib.MediaFramework.MediaRenderer.Renderer.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam, IntPtr uIdSubclass, IntPtr dwRefData)

**Comment by SuRGeoNix** [comment]
@ansdy29 I will need more information to resolve this if it is an issue with the library

**Comment by SuRGeoNix** [comment]
Closing this until a reproduceable way will be provided or detailed explanation/logs
